title: PeakAnalyser
description: A freeware Windows application for visualizing heating demand profiles and analysing peak load shifting feasibility.
theme: jekyll-theme-cayman
lang: en
show_downloads: false